**PyTorchとは？**  
https://colab.research.google.com/github/YutaroOgawa/pytorch_tutorials_jp/blob/main/notebook/1_Learning%20PyTorch/1_1_tensor_tutorial_jp.ipynb

In [1]:
%matplotlib inline

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[9.9783e+15, 4.5664e-41, 9.9783e+15],
        [4.5664e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 3.0313e+32],
        [6.7994e+22, 4.8617e+30, 6.4640e-04],
        [1.3563e-19, 1.3563e-19, 1.3563e-19]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4859, 0.5460, 0.5858],
        [0.6360, 0.3939, 0.1959],
        [0.7803, 0.8547, 0.4747],
        [0.3008, 0.0041, 0.5888],
        [0.0475, 0.7988, 0.5277]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1276, -0.2721,  1.8721],
        [-0.6205, -0.8462,  1.4882],
        [ 1.5604,  0.1679, -0.8689],
        [ 0.3715, -0.7353,  1.4762],
        [ 0.5158, -0.4241, -0.1979]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5785,  0.0378,  2.7754],
        [-0.3080, -0.6771,  2.2754],
        [ 1.7132,  1.0041, -0.3094],
        [ 0.6676, -0.0246,  1.6722],
        [ 0.7416, -0.2312,  0.5738]])


In [10]:
print(torch.add(x, y))

tensor([[ 1.5785,  0.0378,  2.7754],
        [-0.3080, -0.6771,  2.2754],
        [ 1.7132,  1.0041, -0.3094],
        [ 0.6676, -0.0246,  1.6722],
        [ 0.7416, -0.2312,  0.5738]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5785,  0.0378,  2.7754],
        [-0.3080, -0.6771,  2.2754],
        [ 1.7132,  1.0041, -0.3094],
        [ 0.6676, -0.0246,  1.6722],
        [ 0.7416, -0.2312,  0.5738]])


In [12]:
y.add_(x)
print(y)

tensor([[ 1.5785,  0.0378,  2.7754],
        [-0.3080, -0.6771,  2.2754],
        [ 1.7132,  1.0041, -0.3094],
        [ 0.6676, -0.0246,  1.6722],
        [ 0.7416, -0.2312,  0.5738]])


In [13]:
print(x[:, 1])

tensor([-0.2721, -0.8462,  0.1679, -0.7353, -0.4241])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9446])
-0.9445686340332031


In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([0.0554], device='cuda:0')
tensor([0.0554], dtype=torch.float64)
